project_id = "rzetgajncoedibmlfyvl"

[functions.import-hypeauditor]
verify_jwt = true

[functions.import-mapped-data]
verify_jwt = true

[functions.create-user]
verify_jwt = true

[functions.fetch-url-preview]
verify_jwt = false

[functions.n8n-content-webhook]
verify_jwt = false

[functions.n8n-ai-insights-webhook]
verify_jwt = false

[functions.proxy-image]
verify_jwt = false

[functions.generate-ai-insights]
verify_jwt = false

[functions.import-meta-campaign-full]
verify_jwt = true

[functions.analyze-instagram-content]
verify_jwt = false

[functions.import-brand-meta-data]
verify_jwt = true

[functions.fetch-ad-previews]
verify_jwt = true

[functions.import-tiktok-ads]
verify_jwt = true

[functions.import-tiktok-demographics]
verify_jwt = true

[functions.generate-space-ai-insights]
verify_jwt = false

[functions.translate-text]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false
